import Head from 'next/head'
import { ChakraProvider, extendTheme, Box, Container } from '@chakra-ui/react'
import '@styles/highlight-dark.css'
import '@styles/table.css'

const theme = extendTheme({
  styles: {
    global: {
      // styles for the `body`
      body: {
        color: 'black',
        padding: '0',
        margin: '0',
        background: 'url(/grid.svg)',
        backgroundSize: '1.5rem 1.5rem',
        fontFamily:
          'KoHo, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
      },
      button: {
        outline: 'none',
        focus: {
          outline: 'none',
        },
      },
      h1: {
        fontSize: '2.5rem',
        fontWeight: 'bold',
      },
      p: {
        marginBottom: '1rem',
        textIndent: '1.5rem',
      },
      code: {
        bg: '#eeeeee',
        color: 'blue.400',
        padding: '.25em .5em',
      },
      pre: {
        marginBottom: '1rem',
      },
      a: {
        color: 'purple.500',
        _hover: {
          textDecoration: 'underline',
        },
      },
    },
  },
})

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <meta
          name="viewport"
          content=" width=device-width, initial-scale=1.0, user-scalable=no"
        />

        <title>gilmar sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider theme={theme}>
        <Box display="flex" flexDirection="column" alignItems="center">
          <Box width={{ sm: '100%', md: '1024px' }}>
            <Component key="app" {...pageProps} />
          </Box>
        </Box>
      </ChakraProvider>
    </>
  )
}

export default MyApp
