import Head from "next/head";

import { Container } from "./styles";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>gilmar sales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      portfolio-blog
      <footer>Gilso</footer>
    </Container>
  );
}
