import Head from 'next/head';
import { Image } from '@chakra-ui/react';

import Navigation from '@components/Navigation';

export default function Home() {
  return (
    <>
      <Head>
        <title>gilmar sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation active="home">
        <Image
          width="40"
          borderRadius="50%"
          src="https://avatars2.githubusercontent.com/u/7975964"
          alt="Segun Adebayo"
        />
        <h1>Atomos</h1>
        <button>botao</button>
        <span>aosdkasodk</span>
        <h1>Moleculas</h1>
        <div>
          <button>registrar</button>
          <button>cancelar</button>
        </div>
        <div>
          <input name="user" />
          <input name="password" />
        </div>
        <h1>Organismos</h1>
        <form>
          <div>
            <input name="user" />
            <input name="password" />
          </div>
          <div>
            <button>registrar</button>
            <button>cancelar</button>
          </div>
        </form>
        ecossistema é o protótipo do ambiente
      </Navigation>

      <footer>Gilso</footer>
    </>
  );
}
