import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>gilmar sales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      portfolio-blog
      <footer>Gilso</footer>
    </div>
  );
}
